name: Cron Webhook

on:
  schedule:
    - cron: "20 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@2.0.2
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          body: "{}"
